// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Scanner.flex

/* ===================================================================
 *  Scanner.flex  –  JFlex specification for the custom language
 *  Produces Yylex.java when processed by JFlex.
 *  Token output matches ManualScanner.java exactly.
 * =================================================================== */

/* ---------- User Code Section ---------- */

import java.util.ArrayList;
import java.util.List;


@SuppressWarnings("fallthrough")
class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING_STATE = 2;
  public static final int CHAR_STATE = 4;
  public static final int MULTICOMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\1\6\1\7\1\0\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\12\23\1\24"+
    "\1\25\1\26\1\27\1\30\2\0\4\31\1\32\25\31"+
    "\1\33\1\34\1\35\1\0\1\36\1\0\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\36\1\45\1\46\1\36"+
    "\1\47\1\50\1\36\1\51\1\52\1\53\1\36\1\54"+
    "\1\55\1\56\1\57\5\36\1\60\1\61\1\62\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\14\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\0\1\41\1\42\1\43\1\0\1\1"+
    "\1\44\1\45\1\3\1\46\1\47\1\50\1\51\1\52"+
    "\1\21\1\53\1\54\1\55\1\56\1\0\1\57\1\60"+
    "\1\61\1\27\1\62\15\32\1\63\1\64\1\65\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\77\1\100\1\0\1\101\1\27\15\32\2\101\1\102"+
    "\1\27\4\32\1\103\3\32\1\104\3\32\1\105\1\101"+
    "\1\0\1\101\1\102\1\101\1\27\1\106\5\32\1\107"+
    "\2\32\1\110\1\101\1\0\1\101\1\27\3\32\1\111"+
    "\1\32\1\112\1\113\2\101\1\27\2\32\1\114\1\32"+
    "\2\101\1\27\1\32\1\115\1\116\1\101\1\117\1\27"+
    "\1\120\26\27\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\314\0\u0132"+
    "\0\314\0\u0165\0\314\0\u0198\0\314\0\314\0\314\0\u01cb"+
    "\0\u01fe\0\314\0\u0231\0\u0264\0\u0297\0\314\0\314\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\314\0\314\0\u0396\0\u03c9\0\u03fc"+
    "\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e\0\u0561\0\u0594"+
    "\0\u05c7\0\314\0\u05fa\0\314\0\u062d\0\314\0\314\0\u0660"+
    "\0\314\0\314\0\314\0\u0693\0\u06c6\0\u06f9\0\314\0\u072c"+
    "\0\314\0\314\0\314\0\314\0\314\0\u075f\0\314\0\314"+
    "\0\314\0\314\0\u0792\0\314\0\314\0\314\0\u07c5\0\u07f8"+
    "\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990"+
    "\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\314\0\314\0\314\0\314\0\314"+
    "\0\314\0\314\0\314\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e"+
    "\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26"+
    "\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe"+
    "\0\u0ef1\0\u0f24\0\u0f57\0\u0396\0\u0f8a\0\u0fbd\0\u0ff0\0\u0396"+
    "\0\u1023\0\u1056\0\u1089\0\u0396\0\u10bc\0\u10ef\0\u1122\0\u1155"+
    "\0\u1155\0\u1188\0\u0396\0\u11bb\0\u11ee\0\u1221\0\u1254\0\u1287"+
    "\0\u0396\0\u12ba\0\u12ed\0\u0396\0\u1320\0\u1155\0\u1353\0\u1386"+
    "\0\u13b9\0\u13ec\0\u141f\0\u0396\0\u1452\0\u0396\0\u0396\0\u1485"+
    "\0\u14b8\0\u14eb\0\u151e\0\u1551\0\u0396\0\u1584\0\u15b7\0\u15ea"+
    "\0\u161d\0\u1650\0\u0396\0\u0396\0\u1683\0\314\0\u16b6\0\u0396"+
    "\0\u16e9\0\u171c\0\u174f\0\u1782\0\u17b5\0\u17e8\0\u181b\0\u184e"+
    "\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3\0\u19e6"+
    "\0\u1a19\0\u1a4c\0\u1a7f\0\u1ab2\0\u1ae5\0\u1b18\0\u07f8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\0\1\6\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\5\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\2\33\1\34\1\5\1\35\2\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\36\1\44\1\36\1\45\1\36"+
    "\1\46\1\36\1\47\1\50\1\51\1\36\1\52\1\53"+
    "\1\54\2\55\1\56\3\55\1\57\25\55\1\60\26\55"+
    "\2\61\1\62\7\61\1\63\21\61\1\64\26\61\61\65"+
    "\1\66\1\65\64\0\1\6\2\0\1\6\105\0\1\67"+
    "\42\0\1\70\51\0\1\71\12\0\1\72\66\0\1\73"+
    "\11\0\1\74\51\0\1\75\4\0\1\76\3\0\1\77"+
    "\53\0\1\100\2\0\1\76\3\0\1\101\62\0\1\102"+
    "\54\0\1\103\1\0\1\25\66\0\1\104\62\0\1\105"+
    "\62\0\1\106\56\0\1\107\5\0\2\110\3\0\22\107"+
    "\26\0\1\36\5\0\2\36\3\0\22\36\26\0\1\36"+
    "\5\0\2\36\3\0\16\36\1\111\3\36\26\0\1\36"+
    "\5\0\2\36\3\0\14\36\1\112\5\36\26\0\1\36"+
    "\5\0\2\36\3\0\5\36\1\113\14\36\26\0\1\36"+
    "\5\0\2\36\3\0\12\36\1\114\7\36\26\0\1\36"+
    "\5\0\2\36\3\0\1\36\1\115\6\36\1\116\10\36"+
    "\1\117\26\0\1\36\5\0\2\36\3\0\13\36\1\120"+
    "\6\36\26\0\1\36\5\0\2\36\3\0\14\36\1\121"+
    "\5\36\26\0\1\36\5\0\2\36\3\0\21\36\1\122"+
    "\26\0\1\36\5\0\2\36\3\0\5\36\1\123\14\36"+
    "\26\0\1\36\5\0\2\36\3\0\20\36\1\124\1\36"+
    "\26\0\1\36\5\0\2\36\3\0\16\36\1\125\3\36"+
    "\64\0\1\126\1\0\2\55\1\0\3\55\1\0\25\55"+
    "\1\0\26\55\2\127\3\0\1\127\1\130\25\127\1\131"+
    "\14\127\1\132\2\127\1\133\1\127\1\134\4\127\2\135"+
    "\3\0\5\135\1\136\21\135\1\137\14\135\1\140\2\135"+
    "\1\141\1\135\1\142\4\135\61\65\1\0\1\65\7\0"+
    "\1\143\53\0\2\70\1\0\60\70\21\0\1\144\1\0"+
    "\1\76\62\0\1\145\62\0\1\146\5\0\2\110\3\0"+
    "\22\146\26\0\1\110\5\0\2\110\3\0\22\110\26\0"+
    "\1\36\5\0\2\36\3\0\5\36\1\147\14\36\26\0"+
    "\1\36\5\0\2\36\3\0\13\36\1\150\6\36\26\0"+
    "\1\36\5\0\2\36\3\0\3\36\1\151\16\36\26\0"+
    "\1\36\5\0\2\36\3\0\17\36\1\152\2\36\26\0"+
    "\1\36\5\0\2\36\3\0\12\36\1\153\7\36\26\0"+
    "\1\36\5\0\2\36\3\0\13\36\1\154\6\36\26\0"+
    "\1\36\5\0\2\36\3\0\13\36\1\155\6\36\26\0"+
    "\1\36\5\0\2\36\3\0\15\36\1\156\4\36\26\0"+
    "\1\36\5\0\2\36\3\0\14\36\1\157\5\36\26\0"+
    "\1\36\5\0\2\36\3\0\20\36\1\160\1\36\26\0"+
    "\1\36\5\0\2\36\3\0\20\36\1\161\1\36\26\0"+
    "\1\36\5\0\2\36\3\0\1\36\1\162\20\36\26\0"+
    "\1\36\5\0\2\36\3\0\21\36\1\163\26\0\1\164"+
    "\62\0\1\165\6\0\1\166\10\0\1\166\42\0\1\167"+
    "\5\0\2\110\3\0\22\167\26\0\1\36\5\0\2\36"+
    "\3\0\1\36\1\170\20\36\26\0\1\36\5\0\2\36"+
    "\3\0\4\36\1\171\13\36\1\172\1\36\26\0\1\36"+
    "\5\0\2\36\3\0\12\36\1\173\7\36\26\0\1\36"+
    "\5\0\2\36\3\0\5\36\1\174\14\36\26\0\1\36"+
    "\5\0\2\36\3\0\17\36\1\163\2\36\26\0\1\36"+
    "\5\0\2\36\3\0\10\36\1\175\11\36\26\0\1\36"+
    "\5\0\2\36\3\0\3\36\1\176\16\36\26\0\1\36"+
    "\5\0\2\36\3\0\21\36\1\177\26\0\1\36\5\0"+
    "\2\36\3\0\15\36\1\200\4\36\26\0\1\36\5\0"+
    "\2\36\3\0\15\36\1\201\4\36\26\0\1\36\5\0"+
    "\2\36\3\0\21\36\1\202\26\0\1\36\5\0\2\36"+
    "\3\0\16\36\1\203\3\36\26\0\1\36\5\0\2\36"+
    "\3\0\5\36\1\204\14\36\26\0\1\205\6\0\1\206"+
    "\10\0\1\206\42\0\1\207\6\0\1\166\10\0\1\166"+
    "\35\0\1\210\1\0\1\210\2\0\1\211\62\0\1\212"+
    "\5\0\2\110\3\0\22\212\26\0\1\36\5\0\2\36"+
    "\3\0\11\36\1\213\10\36\26\0\1\36\5\0\2\36"+
    "\3\0\10\36\1\214\11\36\26\0\1\36\5\0\2\36"+
    "\3\0\10\36\1\215\11\36\26\0\1\36\5\0\2\36"+
    "\3\0\1\36\1\216\20\36\26\0\1\36\5\0\2\36"+
    "\3\0\17\36\1\217\2\36\26\0\1\36\5\0\2\36"+
    "\3\0\20\36\1\220\1\36\26\0\1\36\5\0\2\36"+
    "\3\0\20\36\1\221\1\36\26\0\1\36\5\0\2\36"+
    "\3\0\21\36\1\222\26\0\1\36\5\0\2\36\3\0"+
    "\16\36\1\223\3\36\26\0\1\36\5\0\2\36\3\0"+
    "\20\36\1\224\1\36\26\0\1\225\6\0\1\206\10\0"+
    "\1\206\35\0\1\226\1\0\1\226\2\0\1\211\62\0"+
    "\1\227\6\0\1\166\10\0\1\166\42\0\1\211\62\0"+
    "\1\230\5\0\2\110\3\0\22\230\26\0\1\36\5\0"+
    "\2\36\3\0\20\36\1\231\1\36\26\0\1\36\5\0"+
    "\2\36\3\0\13\36\1\232\6\36\26\0\1\36\5\0"+
    "\2\36\3\0\16\36\1\233\3\36\26\0\1\36\5\0"+
    "\2\36\3\0\7\36\1\234\12\36\26\0\1\36\5\0"+
    "\2\36\3\0\10\36\1\235\11\36\26\0\1\36\5\0"+
    "\2\36\3\0\20\36\1\236\1\36\26\0\1\36\5\0"+
    "\2\36\3\0\13\36\1\237\6\36\26\0\1\240\6\0"+
    "\1\206\10\0\1\206\42\0\1\241\6\0\1\166\10\0"+
    "\1\166\42\0\1\242\5\0\2\110\3\0\22\242\26\0"+
    "\1\36\5\0\2\36\3\0\10\36\1\243\11\36\26\0"+
    "\1\36\5\0\2\36\3\0\21\36\1\244\26\0\1\36"+
    "\5\0\2\36\3\0\5\36\1\245\14\36\26\0\1\36"+
    "\5\0\2\36\3\0\14\36\1\246\5\36\26\0\1\247"+
    "\6\0\1\206\10\0\1\206\42\0\1\250\6\0\1\166"+
    "\10\0\1\166\42\0\1\251\5\0\2\110\3\0\22\251"+
    "\26\0\1\36\5\0\2\36\3\0\14\36\1\252\5\36"+
    "\26\0\1\36\5\0\2\36\3\0\5\36\1\253\14\36"+
    "\26\0\1\36\5\0\2\36\3\0\13\36\1\254\6\36"+
    "\26\0\1\255\6\0\1\206\10\0\1\206\42\0\1\256"+
    "\6\0\1\166\10\0\1\166\42\0\1\257\5\0\2\110"+
    "\3\0\22\257\26\0\1\36\5\0\2\36\3\0\13\36"+
    "\1\260\6\36\26\0\1\256\6\0\1\206\10\0\1\206"+
    "\42\0\1\261\5\0\2\110\3\0\22\261\26\0\1\262"+
    "\5\0\2\110\3\0\22\262\26\0\1\263\5\0\2\110"+
    "\3\0\22\263\26\0\1\264\5\0\2\110\3\0\22\264"+
    "\26\0\1\265\5\0\2\110\3\0\22\265\26\0\1\266"+
    "\5\0\2\110\3\0\22\266\26\0\1\267\5\0\2\110"+
    "\3\0\22\267\26\0\1\270\5\0\2\110\3\0\22\270"+
    "\26\0\1\271\5\0\2\110\3\0\22\271\26\0\1\272"+
    "\5\0\2\110\3\0\22\272\26\0\1\273\5\0\2\110"+
    "\3\0\22\273\26\0\1\274\5\0\2\110\3\0\22\274"+
    "\26\0\1\275\5\0\2\110\3\0\22\275\26\0\1\276"+
    "\5\0\2\110\3\0\22\276\26\0\1\277\5\0\2\110"+
    "\3\0\22\277\26\0\1\300\5\0\2\110\3\0\22\300"+
    "\26\0\1\301\5\0\2\110\3\0\22\301\26\0\1\302"+
    "\5\0\2\110\3\0\22\302\26\0\1\303\5\0\2\110"+
    "\3\0\22\303\26\0\1\304\5\0\2\110\3\0\22\304"+
    "\26\0\1\305\5\0\2\110\3\0\22\305\26\0\1\306"+
    "\5\0\2\110\3\0\22\306\26\0\1\307\5\0\2\110"+
    "\3\0\22\307\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6987];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\1\1\11\1\1\1\11\1\1\1\11\1\1"+
    "\1\11\1\1\3\11\2\1\1\11\3\1\2\11\4\1"+
    "\2\11\14\1\1\11\1\1\1\11\1\1\2\11\1\0"+
    "\3\11\1\0\2\1\1\11\1\1\5\11\1\1\4\11"+
    "\1\0\3\11\17\1\16\11\1\0\41\1\1\0\17\1"+
    "\1\0\27\1\1\11\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[199];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /* ----- helpers accessible inside generated scanner ----- */
    private ErrorHandler  errors  = new ErrorHandler();
    private SymbolTable   symbols = new SymbolTable();

    public  ErrorHandler  errs()  { return errors;  }
    public  SymbolTable   syms()  { return symbols;  }

    /** convenience: 1-based line */
    private int ln()  { return yyline + 1; }
    /** convenience: 1-based column */
    private int col() { return yycolumn + 1; }

    /** build a token at current position */
    private Token tok(TokenType t) {
        return new Token(t, yytext(), ln(), col());
    }
    private Token tok(TokenType t, String lex) {
        return new Token(t, lex, ln(), col());
    }

    /** register identifier in symbol table */
    private void addSym(String name) {
        symbols.add(name, "N/A", "Global", ln());
    }
    /* ----- string / char accumulators ----- */
    private StringBuilder strBuf;
    private int           strLine;
    private int           strCol;
    private boolean       strHasError;

    private StringBuilder chrBuf;
    private int           chrLine;
    private int           chrCol;
    private int           chrCount;        /* characters inside the quotes */
    private boolean       chrHasEscape;
    private boolean       chrHasError;

    /* ----- multi-line comment tracking ----- */
    private int cmtLine;
    private int cmtCol;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case STRING_STATE: {
              errors.noCloseStr(strLine, strCol, strBuf.toString());
                yybegin(YYINITIAL);
                return new Token(TokenType.ERROR, strBuf.toString(), strLine, strCol);
            }  // fall though
            case 200: break;
            case CHAR_STATE: {
              errors.noCloseChr(chrLine, chrCol, chrBuf.toString());
                yybegin(YYINITIAL);
                return new Token(TokenType.ERROR, chrBuf.toString(), chrLine, chrCol);
            }  // fall though
            case 201: break;
            case MULTICOMMENT: {
              errors.noCloseCmnt(cmtLine, cmtCol, "#|...");
                    yybegin(YYINITIAL);
                    return tok(TokenType.EOF, "EOF");
            }  // fall though
            case 202: break;
            default:
              {
                return tok(TokenType.EOF, "EOF");
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* consume */
            }
          // fall through
          case 82: break;
          case 2:
            { errors.badChar(ln(), col(), yytext());
                return tok(TokenType.ERROR);
            }
          // fall through
          case 83: break;
          case 3:
            { /* skip */
            }
          // fall through
          case 84: break;
          case 4:
            { /* skip, line tracking automatic */
            }
          // fall through
          case 85: break;
          case 5:
            { return tok(TokenType.LOGICAL_NOT);
            }
          // fall through
          case 86: break;
          case 6:
            { strBuf = new StringBuilder("\"");
            strLine = ln(); strCol = col();
            strHasError = false;
            yybegin(STRING_STATE);
            }
          // fall through
          case 87: break;
          case 7:
            { return tok(TokenType.MODULO);
            }
          // fall through
          case 88: break;
          case 8:
            { errors.badChar(ln(), col(), "&");
                return tok(TokenType.ERROR, "&");
            }
          // fall through
          case 89: break;
          case 9:
            { chrBuf = new StringBuilder("'");
            chrLine = ln(); chrCol = col();
            chrCount = 0;
            chrHasEscape = false;
            chrHasError = false;
            yybegin(CHAR_STATE);
            }
          // fall through
          case 90: break;
          case 10:
            { return tok(TokenType.LPAREN);
            }
          // fall through
          case 91: break;
          case 11:
            { return tok(TokenType.RPAREN);
            }
          // fall through
          case 92: break;
          case 12:
            { return tok(TokenType.MULTIPLY);
            }
          // fall through
          case 93: break;
          case 13:
            { return tok(TokenType.PLUS);
            }
          // fall through
          case 94: break;
          case 14:
            { return tok(TokenType.COMMA);
            }
          // fall through
          case 95: break;
          case 15:
            { return tok(TokenType.MINUS);
            }
          // fall through
          case 96: break;
          case 16:
            { return tok(TokenType.DIVIDE);
            }
          // fall through
          case 97: break;
          case 17:
            { return tok(TokenType.INTEGER);
            }
          // fall through
          case 98: break;
          case 18:
            { return tok(TokenType.COLON);
            }
          // fall through
          case 99: break;
          case 19:
            { return tok(TokenType.SEMICOLON);
            }
          // fall through
          case 100: break;
          case 20:
            { return tok(TokenType.LESS_THAN);
            }
          // fall through
          case 101: break;
          case 21:
            { return tok(TokenType.ASSIGN);
            }
          // fall through
          case 102: break;
          case 22:
            { return tok(TokenType.GREATER_THAN);
            }
          // fall through
          case 103: break;
          case 23:
            { String id = yytext();
                addSym(id);
                return tok(TokenType.IDENTIFIER);
            }
          // fall through
          case 104: break;
          case 24:
            { return tok(TokenType.LBRACKET);
            }
          // fall through
          case 105: break;
          case 25:
            { return tok(TokenType.RBRACKET);
            }
          // fall through
          case 106: break;
          case 26:
            { errors.log("Invalid Identifier", ln(), col(), yytext(),
                        "Identifiers must start with an uppercase letter [A-Z].");
                return tok(TokenType.ERROR);
            }
          // fall through
          case 107: break;
          case 27:
            { return tok(TokenType.LBRACE);
            }
          // fall through
          case 108: break;
          case 28:
            { errors.badChar(ln(), col(), "|");
                return tok(TokenType.ERROR, "|");
            }
          // fall through
          case 109: break;
          case 29:
            { return tok(TokenType.RBRACE);
            }
          // fall through
          case 110: break;
          case 30:
            { strBuf.append(yytext());
            }
          // fall through
          case 111: break;
          case 31:
            { errors.noCloseStr(strLine, strCol, strBuf.toString());
                yybegin(YYINITIAL);
                return new Token(TokenType.ERROR, strBuf.toString(), strLine, strCol);
            }
          // fall through
          case 112: break;
          case 32:
            { strBuf.append("\"");
                yybegin(YYINITIAL);
                if (strHasError)
                    return new Token(TokenType.ERROR, strBuf.toString(), strLine, strCol);
                return new Token(TokenType.STRING, strBuf.toString(), strLine, strCol);
            }
          // fall through
          case 113: break;
          case 33:
            { chrBuf.append(yytext()); chrCount++;
            }
          // fall through
          case 114: break;
          case 34:
            { errors.noCloseChr(chrLine, chrCol, chrBuf.toString());
                yybegin(YYINITIAL);
                return new Token(TokenType.ERROR, chrBuf.toString(), chrLine, chrCol);
            }
          // fall through
          case 115: break;
          case 35:
            { yybegin(YYINITIAL);
                if (chrCount == 0) {
                    /* empty char literal '' */
                    errors.badLit(chrLine, chrCol, "''", "Empty character literal.");
                    return new Token(TokenType.ERROR, "''", chrLine, chrCol);
                }
                if (chrCount > 1) {
                    chrBuf.append("'");
                    errors.badLit(chrLine, chrCol, chrBuf.toString(),
                            "Character literal contains more than one character.");
                    return new Token(TokenType.ERROR, chrBuf.toString(), chrLine, chrCol);
                }
                chrBuf.append("'");
                if (chrHasError)
                    return new Token(TokenType.ERROR, chrBuf.toString(), chrLine, chrCol);
                return new Token(TokenType.CHAR, chrBuf.toString(), chrLine, chrCol);
            }
          // fall through
          case 116: break;
          case 36:
            { /* consume lone pipe */
            }
          // fall through
          case 117: break;
          case 37:
            { return tok(TokenType.NOT_EQUAL);
            }
          // fall through
          case 118: break;
          case 38:
            { cmtLine = ln(); cmtCol = col();
                yybegin(MULTICOMMENT);
            }
          // fall through
          case 119: break;
          case 39:
            { return tok(TokenType.LOGICAL_AND);
            }
          // fall through
          case 120: break;
          case 40:
            { return tok(TokenType.POWER);
            }
          // fall through
          case 121: break;
          case 41:
            { return tok(TokenType.MULT_ASSIGN);
            }
          // fall through
          case 122: break;
          case 42:
            { return tok(TokenType.INCREMENT);
            }
          // fall through
          case 123: break;
          case 43:
            { return tok(TokenType.PLUS_ASSIGN);
            }
          // fall through
          case 124: break;
          case 44:
            { return tok(TokenType.DECREMENT);
            }
          // fall through
          case 125: break;
          case 45:
            { return tok(TokenType.MINUS_ASSIGN);
            }
          // fall through
          case 126: break;
          case 46:
            { return tok(TokenType.DIV_ASSIGN);
            }
          // fall through
          case 127: break;
          case 47:
            { return tok(TokenType.LESS_EQUAL);
            }
          // fall through
          case 128: break;
          case 48:
            { return tok(TokenType.EQUAL);
            }
          // fall through
          case 129: break;
          case 49:
            { return tok(TokenType.GREATER_EQUAL);
            }
          // fall through
          case 130: break;
          case 50:
            { errors.log("Invalid Identifier", ln(), col(), yytext(),
                        "Identifiers may only contain lowercase letters, digits, and underscores after the first character.");
                return tok(TokenType.ERROR);
            }
          // fall through
          case 131: break;
          case 51:
            { return tok(TokenType.LOGICAL_OR);
            }
          // fall through
          case 132: break;
          case 52:
            { errors.badEsc(strLine, strCol, yytext());
                strBuf.append(yytext());
                strHasError = true;
            }
          // fall through
          case 133: break;
          case 53:
            { strBuf.append("\\\"");
            }
          // fall through
          case 134: break;
          case 54:
            { strBuf.append("\\\\");
            }
          // fall through
          case 135: break;
          case 55:
            { strBuf.append("\\n");
            }
          // fall through
          case 136: break;
          case 56:
            { strBuf.append("\\r");
            }
          // fall through
          case 137: break;
          case 57:
            { strBuf.append("\\t");
            }
          // fall through
          case 138: break;
          case 58:
            { errors.badEsc(chrLine, chrCol, yytext());
                chrBuf.append(yytext());
                chrCount++;
                chrHasError = true;
            }
          // fall through
          case 139: break;
          case 59:
            { chrBuf.append("\\'");  chrCount++; chrHasEscape = true;
            }
          // fall through
          case 140: break;
          case 60:
            { chrBuf.append("\\\\"); chrCount++; chrHasEscape = true;
            }
          // fall through
          case 141: break;
          case 61:
            { chrBuf.append("\\n");  chrCount++; chrHasEscape = true;
            }
          // fall through
          case 142: break;
          case 62:
            { chrBuf.append("\\r");  chrCount++; chrHasEscape = true;
            }
          // fall through
          case 143: break;
          case 63:
            { chrBuf.append("\\t");  chrCount++; chrHasEscape = true;
            }
          // fall through
          case 144: break;
          case 64:
            { yybegin(YYINITIAL);
            }
          // fall through
          case 145: break;
          case 65:
            { return tok(TokenType.FLOAT);
            }
          // fall through
          case 146: break;
          case 66:
            { errors.badLit(ln(), col(), yytext(),
                        "Exponent part of float is incomplete.");
                return tok(TokenType.ERROR);
            }
          // fall through
          case 147: break;
          case 67:
            { return tok(TokenType.ELSE);
            }
          // fall through
          case 148: break;
          case 68:
            { return tok(TokenType.LOOP);
            }
          // fall through
          case 149: break;
          case 69:
            { return tok(TokenType.BOOLEAN);
            }
          // fall through
          case 150: break;
          case 70:
            { return tok(TokenType.BREAK);
            }
          // fall through
          case 151: break;
          case 71:
            { return tok(TokenType.INPUT);
            }
          // fall through
          case 152: break;
          case 72:
            { return tok(TokenType.START);
            }
          // fall through
          case 153: break;
          case 73:
            { return tok(TokenType.FINISH);
            }
          // fall through
          case 154: break;
          case 74:
            { return tok(TokenType.OUTPUT);
            }
          // fall through
          case 155: break;
          case 75:
            { return tok(TokenType.RETURN);
            }
          // fall through
          case 156: break;
          case 76:
            { return tok(TokenType.DECLARE);
            }
          // fall through
          case 157: break;
          case 77:
            { return tok(TokenType.CONTINUE);
            }
          // fall through
          case 158: break;
          case 78:
            { return tok(TokenType.FUNCTION);
            }
          // fall through
          case 159: break;
          case 79:
            { errors.badLit(ln(), col(), yytext(),
                        "Float literal exceeds maximum of 6 decimal digits.");
                return tok(TokenType.ERROR);
            }
          // fall through
          case 160: break;
          case 80:
            { return tok(TokenType.CONDITION);
            }
          // fall through
          case 161: break;
          case 81:
            { errors.longId(ln(), col(), yytext());
                return tok(TokenType.ERROR);
            }
          // fall through
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
